name: 'PR Description Validator'
description: 'Check if PR description matches configured convention'

inputs:
  pr_id:
    required: true
    description: "Pull request ID such as '2'"
  repo:
    required: true
    description: "Repository URL such as 'https://github.com/willianantunes/testing-repository'"

runs:
  using: "composite"
  steps:
    - name: Check PR description
      shell: bash
      run: |
        python ${{ github.action_path }}/pr_description_handler.py \
        --repo "${{ inputs.repo }}" \
        --pull-request-id "${{ inputs.pr_id }}"
