name: Evaluate PR best practices

on:
  workflow_call:

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: "Evaluate code size and apply label"
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          IGNORED: |
            yarn.lock
            poetry.lock
        with:
          sizes: >
            {
              "50": "code size: excellent",
              "150": "code size: good",
              "250": "code size: large",
              "251": "code size: too large"
            }
  random-output-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: willianantunes/reusable-workflows
          path: .reusable-workflows
      - name: Local Action Call
        id: local-action
        uses: ./.reusable-workflows/shared/random-output-1
      - name: Local Action Output
        run: echo "${{ steps.local-action.outputs.random }}"
  random-output-one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Situational questions..."
