name: Evaluate PR best practices

on:
  workflow_call:

jobs:
  commit-checker:
    if: >-
      github.event_name == 'pull_request' && 
      (github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened')
    name: "Check commit messages for Conventional Commits formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: willianantunes/reusable-workflows
          path: .reusable-workflows
      - name: Check commits
        uses: ./.reusable-workflows/shared/commit_checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr_id: ${{ github.event.pull_request.number }}
          repo: ${{ github.event.repository.html_url }}
  label-checker:
    if: >-
      github.event_name == 'pull_request' && 
      (github.event.action == 'synchronize' || github.event.action == 'reopened' || github.event.action == 'labeled' || github.event.action == 'unlabeled')
    name: "Check if required labels are present"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: willianantunes/reusable-workflows
          path: .reusable-workflows
      - name: Check labels
        uses: ./.reusable-workflows/shared/label_checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr_id: ${{ github.event.pull_request.number }}
          repo: ${{ github.event.repository.html_url }}
  validate-pr-description:
    if: >-
      github.event_name == 'pull_request' && (github.event.action == 'edited' || github.event.action == 'opened')
    name: "Check links in the description"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: willianantunes/reusable-workflows
          path: .reusable-workflows
      - name: Check description
        uses: ./.reusable-workflows/shared/pr_description_validator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr_id: ${{ github.event.pull_request.number }}
          repo: ${{ github.event.repository.html_url }}
  comment:
    # It will run only once, when the PR opens
    if: >-
      github.event_name == 'pull_request' && github.event.action == 'opened'
    name: "Insert welcome comment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: willianantunes/reusable-workflows
          path: .reusable-workflows
      - run: ls -la
      - run: cat ./.reusable-workflows/settings/comment.md
      - name: "Comment about important documents"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment $PR --body="$(cat ./.reusable-workflows/settings/comment.md)"
  validate-pr-title:
    if: >-
      github.event_name == 'pull_request' && 
      (github.event.action == 'edited' || github.event.action == 'opened')
    name: "Validate PR title"
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  triage:
    if: >-
      github.event_name == 'pull_request' && 
      (github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened')
    name: "Basic triage"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: willianantunes/reusable-workflows
          path: .reusable-workflows
      - uses: actions/labeler@v4
        with:
          sync-labels: true
          configuration-path: ./.reusable-workflows/settings/labeler.yml
  size-label:
    if: >-
      github.event_name == 'pull_request' && 
      (github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened')
    name: "Evaluate code size and apply label"
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # https://github.com/pascalgn/size-label-action/blob/b1f4946f381d38d3b5960f76b514afdfef39b609/index.js#L117
          DEBUG_ACTION: true
          IGNORED: |
            yarn.lock
            package-lock.json
            poetry.lock
        with:
          sizes: >
            {
              "0": "excellent",
              "100": "good",
              "200": "large",
              "250": "huge",
              "500": "enormous"
            }
