name: Evaluate PR best practices

on:
  workflow_call:

jobs:
  random-output-1:
    runs-on: ubuntu-latest
    steps:
      - name: Local Action Call
        id: local-action
        uses: willianantunes/reusable-workflows/.github/workflows/shared/random-output-1@main
      - name: Local Action Output
        run: echo "${{ steps.local-action.outputs.random }}"
  random-output-one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Situational questions..."
