name: Evaluate PR best practices

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: willianantunes/reusable-workflows
          path: .reusable-workflows
      - uses: actions/labeler@v4
        with:
          sync-labels: true
          configuration-path: ./.reusable-workflows/settings/labeler.yml
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: "Evaluate code size and apply label"
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # https://github.com/pascalgn/size-label-action/blob/b1f4946f381d38d3b5960f76b514afdfef39b609/index.js#L117
          DEBUG_ACTION: true
          IGNORED: |
            yarn.lock
            package-lock.json
            poetry.lock
        with:
          sizes: >
            {
              "0": "excellent",
              "100": "good",
              "200": "large",
              "250": "huge",
              "500": "enormous"
            }
