name: Evaluate PR best practices

on:
  workflow_call:

jobs:
  comment:
#    if: >-
#      github.event.pull_request.opened != 'octobot' &&
#      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event) }}'
      - run: echo "event name is:" ${{ github.event }}
      - run: echo "event name is:" ${{ github.event_name }}
      - run: echo "event type is:" ${{ github.event.action }}
#      - name: "Comment about changes we can't accept"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PR: ${{ github.event.pull_request.html_url }}
#        run: |
#          gh pr edit $PR --add-label 'invalid'
#          gh pr comment $PR --body 'It looks like you edited `package*.json`, `.github/CODEOWNERS`, or `.github/workflows/**`. We do not allow contributions to these files. Please review our [contributing guidelines](https://github.com/octo-org/octo-repo/blob/main/CONTRIBUTING.md) for what contributions are accepted.'
  validate-pr-title:
    name: "Validate PR title"
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  triage:
    name: "Basic triage"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: willianantunes/reusable-workflows
          path: .reusable-workflows
      - uses: actions/labeler@v4
        with:
          sync-labels: true
          configuration-path: ./.reusable-workflows/settings/labeler.yml
  size-label:
    name: "Evaluate code size and apply label"
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # https://github.com/pascalgn/size-label-action/blob/b1f4946f381d38d3b5960f76b514afdfef39b609/index.js#L117
          DEBUG_ACTION: true
          IGNORED: |
            yarn.lock
            package-lock.json
            poetry.lock
        with:
          sizes: >
            {
              "0": "excellent",
              "100": "good",
              "200": "large",
              "250": "huge",
              "500": "enormous"
            }
