name: Evaluate PR best practices

on:
  workflow_call:

jobs:
  random-output-1:
    runs-on: ubuntu-latest
    steps:
      # Necessary to access local action
      # https://stackoverflow.com/a/75735736/3899136
      - uses: actions/checkout@v3
        with:
          repository: willianantunes/reusable-workflows
          path: .reusable-workflows
      - name: Local Action Call
        id: local-action
        uses: ./.reusable-workflows/shared/random-output-1
      - name: Local Action Output
        run: echo "${{ steps.local-action.outputs.random }}"
  random-output-one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Situational questions..."
